# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 PitPact contributors
#
# PitPact — M5-Closeout Bucket 1 (Six Cultures)
# test net.
#
# The M5-Closeout Bucket 1 deliverable
# (per ADR-0017) is the canonical "six
# cultures" expansion. The carrier is
# `PlayableShell.build()`; the UI
# renders portraits per culture.
# The test net exercises:
#
#   1. The factory returns 6 inhabitants
#      (one per culture).
#   2. The 6 culture IDs are the
#      canonical M2 Track A + M3
#      Closeout setup (lanternbearer,
#      bellows, ember, ledger,
#      silvershroud, tide).
#   3. The 6 portrait PNGs exist
#      (procedurally generated).
#   4. The UI's `_portrait_path_for_culture`
#      mapping is correct for all 6.
extends GutTest

const _PS_PATH: String = "res://src/ui/playable_shell.gd"
const _PSUI_PATH: String = "res://src/ui/playable_shell_ui.gd"
const _EXPECTED_CULTURES: Array = [
	"lanternbearer",
	"bellows",
	"ember",
	"ledger",
	"silvershroud",
	"tide",
]
const _EXPECTED_PORTRAITS: Array = [
	"lanternbearer_scribe.png",
	"bellows.png",
	"ember.png",
	"ledger.png",
	"silvershroud.png",
	"tide.png",
]


func test_six_cultures_count() -> void:
	# The M5-Closeout Bucket 1
	# deliverable: 6 inhabitants
	# (one per culture). The test
	# pins the canonical count.
	var PS: GDScript = load(_PS_PATH)
	var built: Dictionary = PS.call("build")
	var inhabitants: Array = built["inhabitants"]
	assert_eq(inhabitants.size(), 6, "PlayableShell.build() returns 6 inhabitants")


func test_six_cultures_ids() -> void:
	# The 6 culture IDs are the
	# canonical M2 Track A + M3
	# Closeout setup. The test
	# collects the cultures from
	# the inhabitants and asserts
	# the canonical set is present.
	var PS: GDScript = load(_PS_PATH)
	var built: Dictionary = PS.call("build")
	var inhabitants: Array = built["inhabitants"]
	var present: Dictionary = {}
	for inh in inhabitants:
		present[String(inh.culture)] = true
	for c in _EXPECTED_CULTURES:
		assert_true(present.has(c), "inhabitant with culture '%s' present" % c)


func test_six_cultures_unique() -> void:
	# The 6 inhabitants must be
	# 6 distinct cultures (no
	# duplicates). The test pins
	# the uniqueness invariant.
	var PS: GDScript = load(_PS_PATH)
	var built: Dictionary = PS.call("build")
	var inhabitants: Array = built["inhabitants"]
	var cultures: Dictionary = {}
	for inh in inhabitants:
		cultures[String(inh.culture)] = true
	assert_eq(cultures.size(), 6, "6 inhabitants have 6 distinct cultures")


func test_six_culture_portrait_assets_exist() -> void:
	# The 6 portrait PNGs are
	# procedurally generated by
	# `tools/assets/generate_assets.gd`.
	# The test asserts each file
	# exists in `assets/inhabitants/`.
	for filename in _EXPECTED_PORTRAITS:
		var path: String = "res://assets/inhabitants/" + String(filename)
		var d: DirAccess = DirAccess.open("res://assets/inhabitants/")
		assert_ne(d, null, "assets/inhabitants/ exists")
		var found: bool = FileAccess.file_exists(path)
		assert_true(found, "portrait %s exists" % path)


func test_six_culture_portrait_paths() -> void:
	# The UI's `_portrait_path_for_culture`
	# method maps each of the 6
	# cultures to a portrait path.
	# The test pins the mapping
	# (a regression that changes
	# a path is caught).
	var PSUI: GDScript = load(_PSUI_PATH)
	var ui: Node = PSUI.new()
	var expected_paths: Dictionary = {
		"lanternbearer": "res://assets/inhabitants/lanternbearer_scribe.png",
		"bellows": "res://assets/inhabitants/bellows.png",
		"ember": "res://assets/inhabitants/ember.png",
		"ledger": "res://assets/inhabitants/ledger.png",
		"silvershroud": "res://assets/inhabitants/silvershroud.png",
		"tide": "res://assets/inhabitants/tide.png",
	}
	for c in expected_paths.keys():
		var path: String = ui.call("_portrait_path_for_culture", c)
		assert_eq(
			String(path),
			String(expected_paths[c]),
			"portrait for '%s' is '%s'" % [c, expected_paths[c]]
		)
	# Settler falls back to
	# `settler.png` (the M4
	# generic).
	var settler_path: String = ui.call("_portrait_path_for_culture", "settler")
	assert_eq(
		String(settler_path),
		"res://assets/inhabitants/settler.png",
		"portrait for 'settler' is 'settler.png'"
	)


func test_six_culture_portrait_fallback() -> void:
	# Unknown cultures fall back
	# to the lanternbearer
	# portrait (the M4 default).
	var PSUI: GDScript = load(_PSUI_PATH)
	var ui: Node = PSUI.new()
	var path: String = ui.call("_portrait_path_for_culture", "unknown_culture")
	assert_eq(
		String(path),
		"res://assets/inhabitants/lanternbearer_scribe.png",
		"unknown culture falls back to lanternbearer_scribe.png"
	)


func test_six_cultures_seeded_deterministic() -> void:
	# The factory is SEED-pinned
	# (per ADR-0005). The test
	# asserts the inhabitants
	# are identical across two
	# builds with the same seed.
	var PS: GDScript = load(_PS_PATH)
	var built1: Dictionary = PS.call("build_with_seed", 4242)
	var built2: Dictionary = PS.call("build_with_seed", 4242)
	var inh1: Array = built1["inhabitants"]
	var inh2: Array = built2["inhabitants"]
	assert_eq(inh1.size(), inh2.size(), "two builds have the same inhabitant count")
	for i in range(inh1.size()):
		assert_eq(
			String(inh1[i].id),
			String(inh2[i].id),
			"inhabitant %d id is identical across builds" % i
		)
		assert_eq(
			String(inh1[i].culture),
			String(inh2[i].culture),
			"inhabitant %d culture is identical across builds" % i
		)
