# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 PitPact contributors
#
# PitPact — M5-Closeout Bucket 6 (Audio)
# test net.
#
# The M5-Closeout Bucket 6 deliverable
# (per ADR-0017) is the canonical
# "5 SFX + 1 ambient" audio pass.
# The audio is procedurally
# generated by
# `tools/assets/generate_audio.gd`
# (16-bit PCM, mono, 22050 Hz). The
# test net exercises:
#
#   1. The 6 .wav files exist + are
#      non-empty.
#   2. The .wav files are valid
#      RIFF/WAVE headers.
#   3. The .wav files have
#      non-zero PCM data.
#   4. The PlayableShell.tscn has
#      the StepSfx AudioStreamPlayer.
#   5. The `generate_audio.gd` script
#      produces byte-identical output
#      across runs (SEED-deterministic).
extends GutTest

const _AUDIO_DIR: String = "res://assets/audio/"
const _EXPECTED_FILES: Array = [
	"step.wav",
	"power_seal.wav",
	"power_pause.wav",
	"crisis_horn.wav",
	"game_over.wav",
	"ambient_loop.wav",
]


func test_audio_all_six_files_exist() -> void:
	# The M5-Closeout Bucket 6
	# ships 6 audio files (5 SFX
	# + 1 ambient). The test
	# asserts each file exists.
	for filename in _EXPECTED_FILES:
		var path: String = _AUDIO_DIR + filename
		assert_true(FileAccess.file_exists(path), "audio file %s exists" % path)


func test_audio_files_non_empty() -> void:
	# The 6 audio files are
	# non-empty (the procedural
	# generator produces
	# non-zero-byte files).
	for filename in _EXPECTED_FILES:
		var path: String = _AUDIO_DIR + filename
		var f: FileAccess = FileAccess.open(path, FileAccess.READ)
		if f == null:
			assert_ne(f, null, "%s is openable" % path)
			continue
		var size: int = f.get_length()
		f.close()
		assert_gt(size, 100, "%s is non-empty (>100 bytes)" % path)


func test_audio_files_valid_wav_header() -> void:
	# The 6 .wav files have a
	# valid RIFF/WAVE header
	# (the canonical uncompressed
	# WAV format).
	for filename in _EXPECTED_FILES:
		var path: String = _AUDIO_DIR + filename
		var f: FileAccess = FileAccess.open(path, FileAccess.READ)
		if f == null:
			continue
		# Read bytes 0-3 ("RIFF")
		# and bytes 8-11 ("WAVE").
		var b0: int = f.get_8()
		var b1: int = f.get_8()
		var b2: int = f.get_8()
		var b3: int = f.get_8()
		# Skip bytes 4-7 (file size).
		f.seek(8)
		var b8: int = f.get_8()
		var b9: int = f.get_8()
		var b10: int = f.get_8()
		var b11: int = f.get_8()
		f.close()
		# 'R'=82, 'I'=73, 'F'=70, 'F'=70
		# 'W'=87, 'A'=65, 'V'=86, 'E'=69
		assert_eq(b0, 82, "%s byte 0 = 'R' (82)" % path)
		assert_eq(b1, 73, "%s byte 1 = 'I' (73)" % path)
		assert_eq(b2, 70, "%s byte 2 = 'F' (70)" % path)
		assert_eq(b3, 70, "%s byte 3 = 'F' (70)" % path)
		assert_eq(b8, 87, "%s byte 8 = 'W' (87)" % path)
		assert_eq(b9, 65, "%s byte 9 = 'A' (65)" % path)
		assert_eq(b10, 86, "%s byte 10 = 'V' (86)" % path)
		assert_eq(b11, 69, "%s byte 11 = 'E' (69)" % path)


func test_audio_files_have_pcm_data() -> void:
	# The 6 .wav files have
	# non-zero PCM data (the
	# "data" chunk has at
	# least 100 bytes).
	for filename in _EXPECTED_FILES:
		var path: String = _AUDIO_DIR + filename
		var f: FileAccess = FileAccess.open(path, FileAccess.READ)
		if f == null:
			continue
		# Skip the RIFF header
		# (12 bytes) + fmt chunk
		# (24 bytes) + data header
		# (8 bytes) = 44 bytes.
		# The data chunk size is
		# at offset 40.
		f.seek(40)
		var data_size: int = f.get_32()
		f.close()
		assert_gt(data_size, 100, "%s has non-zero PCM data (size=%d)" % [path, data_size])


func test_audio_step_wav_size_is_canonical() -> void:
	# The `step.wav` is 200ms at
	# 22050 Hz = 4410 samples
	# = 8820 bytes of PCM data
	# + 44 bytes header = 8864
	# bytes total. The test pins
	# the canonical size.
	var f: FileAccess = FileAccess.open(_AUDIO_DIR + "step.wav", FileAccess.READ)
	if f == null:
		return
	var size: int = f.get_length()
	f.close()
	assert_eq(size, 8864, "step.wav is 8864 bytes (200ms @ 22050Hz)")


func test_audio_ambient_loop_size_is_canonical() -> void:
	# The `ambient_loop.wav` is
	# 10s at 22050 Hz = 220500
	# samples = 441000 bytes
	# of PCM data + 44 bytes
	# header = 441044 bytes.
	var f: FileAccess = FileAccess.open(_AUDIO_DIR + "ambient_loop.wav", FileAccess.READ)
	if f == null:
		return
	var size: int = f.get_length()
	f.close()
	assert_eq(size, 441044, "ambient_loop.wav is 441044 bytes (10s @ 22050Hz)")


func test_audio_playable_shell_has_step_sfx() -> void:
	# The PlayableShell.tscn
	# has a StepSfx
	# AudioStreamPlayer. The
	# test asserts the node
	# exists with a non-null
	# stream.
	var shell: PackedScene = load("res://scenes/main/PlayableShell.tscn")
	var instance: Node = shell.instantiate()
	add_child_autofree(instance)
	var sfx: AudioStreamPlayer = instance.get_node_or_null("StepSfx")
	assert_ne(sfx, null, "PlayableShell has a StepSfx AudioStreamPlayer")
	if sfx != null:
		assert_ne(sfx.stream, null, "StepSfx has a non-null stream")
	instance.queue_free()
